@baseUrl = http://localhost:3000

### Buscar todos os usuários
GET {{baseUrl}}/users

### Cadastrar um novo usuário
POST {{baseUrl}}/register
Content-Type: application/json

{
  "nome": "rey fennix",
  "curso": "Eng de Software",
  "ra": 1180011
}

### Atualizar curso de um usuário
PATCH {{baseUrl}}/users/16
Content-Type: application/json

{
  "ra": 112611900
}

### Remover um usuário
DELETE {{baseUrl}}/users/
