@baseUrl = http://localhost:3000

### Buscar todos os usuários
GET {{baseUrl}}/hello

### Cadastrar um novo usuário
POST {{baseUrl}}/register
Content-Type: application/json

{
  "nome": "Kaina",
  "curso": "ADS",
  "ra": 112912780
}

### Atualizar curso de um usuário
PATCH {{baseUrl}}/users/3
Content-Type: application/json

{
  "nome": "deives"
}

### Remover um usuário
DELETE {{baseUrl}}/users/2
